#!/usr/bin/env python3
"""Cardiorenal biomarker context container.

Earlier versions assigned unvalidated severity and treatment recommendations
from fixed biomarker thresholds. This version keeps the public API but limits
output to transparent kidney-function categorization and raw biomarker context.
"""

from dataclasses import dataclass
from typing import Any, Dict

from cardiorenal_syndrome_agent.engine import kdigo_gfr_category


@dataclass
class CardiorenalBiomarkers:
    bnp_pg_ml: float
    ntproBnp_pg_ml: float
    creatinine_mg_dl: float
    egfr: float
    cystatin_c_mg_l: float = 0.0
    troponin_ng_ml: float = 0.0
    galectin_3_ng_ml: float = 0.0
    sstd1_ng_ml: float = 0.0
    klotho_pg_ml: float = 0.0


def integrate_biomarkers(biomarkers: CardiorenalBiomarkers) -> Dict[str, Any]:
    gfr = kdigo_gfr_category(biomarkers.egfr)
    return {
        "cardiac_stress": "not_classified",
        "renal_function": gfr["category"],
        "renal_function_description": gfr["description"],
        "fibrosis_risk": "not_calculated",
        "mortality_risk": "not_calculated",
        "overall_severity_score": None,
        "crs_severity": "not_calculated",
        "recommendation": "No treatment recommendation is generated by this module.",
        "bnp": biomarkers.bnp_pg_ml,
        "ntprobnp": biomarkers.ntproBnp_pg_ml,
        "troponin": biomarkers.troponin_ng_ml,
        "creatinine": biomarkers.creatinine_mg_dl,
        "egfr": biomarkers.egfr,
        "note": (
            "Biomarker interpretation depends on assay, reference interval, clinical "
            "setting, age, rhythm, and kidney function."
        ),
    }


class BiomarkerIntegrationAgent:
    def __init__(self):
        self.agent_name = "BiomarkerIntegrationAgent"

    def evaluate(self, biomarkers: CardiorenalBiomarkers) -> Dict[str, Any]:
        return {
            "biomarker_result": integrate_biomarkers(biomarkers),
            "alerts": [],
        }
