#!/usr/bin/env python3
"""CRS type and KDIGO GFR-category reference helpers.

The retained function signature is compatible with earlier releases, but this
module no longer produces an unvalidated prognosis score or treatment plan.
"""

from typing import Any, Dict

from cardiorenal_syndrome_agent.engine import classify_crs_type, kdigo_gfr_category


def classify_crs(
    crs_type: str,
    egfr: float,
    bnp: float = 0.0,
    creatinine: float = 0.0,
    age: float = 65.0,
    diabetes: bool = False,
    hypertension: bool = False,
) -> Dict[str, Any]:
    classification = classify_crs_type(crs_type)
    gfr = kdigo_gfr_category(egfr)
    return {
        "crs_type": classification["crs_type"],
        "type_name": classification["label"],
        "primary_process": classification["primary_process"],
        "secondary_process": classification["secondary_process"],
        "stage": gfr["category"],
        "stage_description": gfr["description"],
        "gfr_category": gfr["category"],
        "gfr_description": gfr["description"],
        "egfr": gfr["egfr"],
        "risk_score": None,
        "risk_factors": [],
        "prognosis": "not_calculated",
        "management": "No treatment recommendation is generated by this module.",
        "context": {
            "bnp": bnp,
            "creatinine": creatinine,
            "age": age,
            "diabetes": bool(diabetes),
            "hypertension": bool(hypertension),
        },
        "note": gfr["ckd_note"],
    }


class CRSStagingAgent:
    def __init__(self):
        self.agent_name = "CRSStagingAgent"

    def evaluate(
        self,
        crs_type: str,
        egfr: float,
        bnp: float = 0.0,
        creatinine: float = 0.0,
        age: float = 65.0,
        diabetes: bool = False,
        hypertension: bool = False,
    ) -> Dict[str, Any]:
        result = classify_crs(
            crs_type,
            egfr,
            bnp,
            creatinine,
            age,
            diabetes,
            hypertension,
        )
        return {
            "staging_result": result,
            "alerts": [],
            "notes": [
                "CRS type is a classification framework, not a stand-alone diagnosis.",
                result["note"],
            ],
        }
